parameters:
    snowcap_core.google_analytics.tracking_id:
    snowcap_core.google_analytics.domain_name:
    snowcap_core.google_analytics.allow_linker:

services:
    # Load twig debug
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags: [ { name: 'twig.extension' } ]
    # Load twig text
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags: [ { name: 'twig.extension' } ]


    # Form types
    snowcap_core.image_type:
        class: Snowcap\CoreBundle\Form\Type\ImageType
        tags:
            - { name: form.type, alias: snowcap_core_image }
        calls:
            - [ setRootDir, [ %kernel.root_dir% ] ]
    snowcap_core.video_type:
        class: Snowcap\CoreBundle\Form\Type\VideoType
        tags:
            - { name: form.type, alias: snowcap_core_video }
    snowcap_core.file_type:
        class: Snowcap\CoreBundle\Form\Type\FileType
        tags:
            - { name: form.type, alias: snowcap_core_file }

    # Field entity event subscriber
    snowcap_core.file_subscriber:
        class: Snowcap\CoreBundle\Listener\FileSubscriber
        arguments: [%kernel.root_dir%]
        tags:
            - { name: doctrine.event_subscriber}

    # Twig extensions
    snowcap_core.twig_navigation:
        class: Snowcap\CoreBundle\Twig\Extension\NavigationExtension
        calls:
            - [ setContainer, [@service_container] ]
        tags:
            - { name: twig.extension }

    snowcap_core.twig_date:
        class: Snowcap\CoreBundle\Twig\Extension\DateExtension
        arguments: [@translator]
        tags:
            - { name: twig.extension }

    snowcap_core.twig_text:
        class: Snowcap\CoreBundle\Twig\Extension\TextExtension
        tags:
            - { name: twig.extension }

    snowcap_core.twig_google:
        class: Snowcap\CoreBundle\Twig\Extension\GoogleExtension
        arguments: [%snowcap_core.google_analytics.tracking_id%]
        calls:
            - [ setDomainName, [%snowcap_core.google_analytics.domain_name%] ]
            - [ setAllowLinker, [%snowcap_core.google_analytics.allow_linker%] ]
        tags:
            - { name: twig.extension }

    # RSS feeds
    snowcap_core.feed_manager:
        class: Snowcap\CoreBundle\Feed\FeedManager

    snowcap_core.request_listener:
        class: Snowcap\CoreBundle\Listener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # Google sitemap
    snowcap_core.sitemap_manager:
        class: Snowcap\CoreBundle\Sitemap\SitemapManager
        arguments: [@validator]